apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: github-push-trigger
spec:
  bindings:
    - ref: github-push-binding
  template:
    ref: github-push-template
  interceptors:
    - ref:
        name: github
      params:
        - name: secretRef
          value:
            secretName: github-secret
            secretKey: secretToken
        - name: eventTypes
          value: ["push"]
    - ref:
        name: "cel"
      params:
        - name: "filter"
          value: "body.ref == 'refs/heads/main'"
        - name: overlays
          value:
           
            - key: repo_url_lower
              expression: "body.repository.clone_url.lowerAscii()"
          
            - key: repo_name_lower
              expression: "body.repository.name.lowerAscii()"
           
            - key: repo_fullname_lower
              expression: "body.repository.full_name.lowerAscii()"  
      
     