apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-app
spec:
  params:
    - name: image
      type: string
    - name: image-latest
      type: string  
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: Dockerfile  

  workspaces:
    - name: source
      description: Workspace where the source code is located
    - name: dockerconfig
      description: Docker config.json с credentials для Docker Hub
      mountPath: /kaniko/.docker
  results:
    - name: IMAGE_DIGEST
      description: Digest of the image just built.
    - name: IMAGE_URL
      description: URL of the image just built.  
    - name: IMAGE_URL_LATEST
      description: URL of the image with latest tag.  
  steps:
    - name: debug-docker-config
      image: alpine
      command: ["/bin/sh"]
      args:
        - -c
        - |
          echo "==== Checking /kaniko/.docker ===="
          ls -la /kaniko/.docker/ || echo "Directory not found"
          echo "==== Content of config.json ===="
          cat /kaniko/.docker/config.json || echo "File not found"
          echo "==== Resolving symlink ===="
          readlink -f /kaniko/.docker/config.json || echo "Not a symlink"
          echo "==== Validating JSON ===="
          cat /kaniko/.docker/config.json | head -c 500
     
    - name: build-and-push
      workingDir: $(workspaces.source.path)/app
      image: gcr.io/kaniko-project/executor:latest
      args:
         - --dockerfile=$(params.DOCKERFILE)
         - --context=.
         - --destination=$(params.image)
         - --destination=$(params.image-latest)
         - --digest-file=$(results.IMAGE_DIGEST.path)
      securityContext:
        runAsUser: 0
      
    
    - name: write-url
      image: docker.io/bash:5.3.0@sha256:6a3e1c2ddbdee552cd69ad8244eee84ad6cc00049c338f700ef5ef247be16f7b
      script: |
        set -e
        image="$(params.image)"
        echo -n "${image}" | tee "$(results.IMAGE_URL.path)"    
        echo -n "$(params.image-latest)" | tee "$(results.IMAGE_URL_LATEST.path)"      
          