apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
spec:
  params:
    - name: repo-url
      value: "$(body.repository.clone_url)"
    - name: revision
      value: "$(body.head_commit.id)"
    - name: branch
      value: "$(body.ref)"
    - name: image
      value: "elpaso5701/{{- lower .body.repository.name }}:$(body.head_commit.id)"
    - name: image-latest
      value: "elpaso5701/{{- lower .body.repository.name }}:latest"  