apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
spec:
  params:
    - name: repo-url
      value: "$(extensions.repo_url_lower)"
    - name: revision
      value: "$(body.head_commit.id)"
    - name: branch
      value: "$(body.ref)"
    - name: image
      value: "elpaso5701/$(extensions.repo_name_lower):$(body.head_commit.id)"
    - name: image-latest
      value: "elpaso5701/$(extensions.repo_name_lower):latest"
 