apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clean-workspace
spec:
  workspaces:
    - name: workspace  
      description: "Workspace to clean"
  steps:
    - name: clean
      image: alpine:latest
      script: |
        #!/bin/sh
        set -e
        
        echo "=== Cleaning workspace: $(workspaces.workspace.path) ==="
        
        rm -rf $(workspaces.workspace.path)/* 2>/dev/null || true
        
        rm -rf $(workspaces.workspace.path)/.[!.]* 2>/dev/null || true
        rm -rf $(workspaces.workspace.path)/..?* 2>/dev/null || true
        
        echo "✅ Workspace cleaned successfully"
        ls -la $(workspaces.workspace.path) || echo "Empty"