apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
      
  workspaces:
    - name: source
      description: Workspace where the source code will be cloned

  steps:
    - name: clone
      image: alpine/git
      workingDir: $(workspaces.source.path)
      env:
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              name: git-secret
              key: token
        - name: REPO_URL
          value: $(params.repo-url)
        - name: REVISION
          value: $(params.revision)
      script: |
        set -e
        
        REPO_PATH=$(echo "${REPO_URL}" | sed 's|https://||' | sed 's|http://||')
        AUTH_URL="https://${GIT_TOKEN}@${REPO_PATH}"
        
        echo "Attempting to clone..."
        git clone "${AUTH_URL}" .
        git checkout "${REVISION}"
       