apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: app-ci-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
    - name: branch
      type: string
    - name: image
      type: string

  workspaces:
    - name: source  
    - name: dockerconfig

  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
    
      workspaces:
        - name: source
               
    - name: build
      runAfter: [clone-repo]
      taskRef:
        name: build-app
      params:
        - name: image
          value: $(params.image)
      workspaces:
        - name: source
        - name: dockerconfig
          