apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-manifests-pvc
  namespace: default   # или тот namespace, где работает Tekton
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi