apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-demo
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      containers:
      - name: gitops-demo
        image: elpaso5701/gitops_demo:f1eb375fab713ac25576f1899c37ceece7154461
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: dockerhub-secret
