apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-push-template
spec:
  params:
    # Оголошуємо параметри, які прийдуть з TriggerBinding
    - name: repo-url
    - name: revision
    - name: branch
    - name: image

  resourcetemplates:
    # Створюємо PipelineRun з параметрами
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: app-build-run-
      spec:
        pipelineRef:
          name: app-ci-pipeline
        params:
          # Використовуємо параметри з TriggerBinding
          - name: repo-url
            value: $(params.repo-url)
          - name: revision
            value: $(params.revision)
          - name: branch
            value: $(params.branch)
          - name: image
            value: $(params.image)
      workspaces:
          - name: source
            emptyDir: {}
          - name: dockerconfig
            secret:
              secretName: dockerhub-secret      