apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
spec:
  replicas: 1  # будет переопределено в overlays
  selector:
    matchLabels:
      app: gitops-demo
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      containers:
        - name: gitops-demo
          image: elpaso5701/gitops_demo:latest  # будет переопределено
          ports:
            - containerPort: 8080