apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: gitops-demo
          image: elpaso5701/gitops_demo:2949372d17ea521daf15f1463c739b91e641c7b1 # Tekton может менять этот тег!
