apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: gitops-demo
          image: elpaso5701/gitops_demo:36530090bae9c3b8d099feeac835ad60947ccd4d # Tekton может менять этот тег!
