apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  
labels:
  - pairs:
      app: gitops-demo
      environment: dev

patches:
  - path: deployment-patch.yaml