apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa

resources:
  - ../../base

labels:
  - pairs:
      app: gitops-demo
      environment: qa

patches:
  - path: deployment-patch.yaml